---
- name: Configure fedora workstation
  hosts: localhost
  vars:
    - hostname: LeosThinkPad
    - default_shell: /usr/bin/fish
  vars_files:
    - ./vars/packages.yaml
    - ./vars/secrets.yml
  vars_prompt:
    - name: ssh_key_passphrase
      prompt: Enter ssh key passphrase
      private: yes
      confirm: yes
  tasks:
    - import_tasks: ./tasks/configure_auto_updates.yml
    - import_tasks: ./tasks/install_repo_packages.yml
    - import_tasks: ./tasks/configure_hostname_and_user.yml
    - import_tasks: ./tasks/generate_ssh_keypair_and_publish.yml
    - import_tasks: ./tasks/configure_dotfiles.yml
    - import_tasks: ./tasks/install_flatpaks.yml
    - import_tasks: ./tasks/install_vscode.yml
    - import_tasks: ./tasks/install_docker.yml
    - import_tasks: ./tasks/install_rust.yml
    - import_tasks: ./tasks/install_cargo_packages.yml
    - import_tasks: ./tasks/install_npm_packages.yml
