---
- name: Add flathub repository to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
- name: Install flatpaks
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flathub_packages }}"
