---
- name: Import a key from a url
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
- name: Add VSCode Repo
  become: true
  ansible.builtin.command:
    cmd: "dnf config-manager --add-repo \
          https://packages.microsoft.com/yumrepos/vscode.repo"
    warn: false
- name: Install VSCode
  become: true
  ansible.builtin.dnf:
    name: code
    state: latest
